"""Data quality — validation failures, severities, and anomaly flags."""
from __future__ import annotations

import sys
from pathlib import Path

import plotly.express as px
import streamlit as st

sys.path.append(str(Path(__file__).resolve().parents[2]))
from dashboard.utils import data  # noqa: E402

st.set_page_config(page_title="Data Quality", page_icon="✅", layout="wide")
st.title("✅ Data Quality & Validation")
st.caption("Configurable rule outcomes from GOVERNANCE.DQ_RESULT + Cortex anomaly flags")

vsum = data.validation_summary()
policies = data.policies()
claims = data.claims()

errors = int(vsum.loc[vsum.SEVERITY == "ERROR", "FAILURE_COUNT"].sum())
warns = int(vsum.loc[vsum.SEVERITY == "WARN", "FAILURE_COUNT"].sum())
pol_anom = int((policies["ANOMALY_SCORE"] >= 0.95).sum())
clm_anom = int((claims["ANOMALY_SCORE"] >= 0.95).sum())

c1, c2, c3, c4 = st.columns(4)
c1.metric("ERROR failures", f"{errors:,}")
c2.metric("WARN failures", f"{warns:,}")
c3.metric("Anomalous policies", pol_anom)
c4.metric("Anomalous claims", clm_anom)

st.divider()

left, right = st.columns(2)
with left:
    st.subheader("Failures by rule")
    fig = px.bar(vsum.sort_values("FAILURE_COUNT", ascending=True),
                 x="FAILURE_COUNT", y="RULE_DESCRIPTION", color="SEVERITY",
                 orientation="h",
                 color_discrete_map={"ERROR": "#e74c3c", "WARN": "#f1c40f", "INFO": "#3498db"})
    fig.update_layout(height=420, yaxis_title="", legend_title="Severity")
    st.plotly_chart(fig, use_container_width=True)

with right:
    st.subheader("Failures by entity & severity")
    grp = vsum.groupby(["ENTITY", "SEVERITY"])["FAILURE_COUNT"].sum().reset_index()
    fig2 = px.bar(grp, x="ENTITY", y="FAILURE_COUNT", color="SEVERITY", barmode="group",
                  color_discrete_map={"ERROR": "#e74c3c", "WARN": "#f1c40f", "INFO": "#3498db"})
    fig2.update_layout(height=420)
    st.plotly_chart(fig2, use_container_width=True)

st.subheader("Rule failure detail")
st.dataframe(vsum.sort_values("FAILURE_COUNT", ascending=False),
             use_container_width=True, hide_index=True)

st.divider()
st.subheader("Top anomalies (Cortex-flagged)")
top_pol = policies.sort_values("ANOMALY_SCORE", ascending=False).head(10)
cols = [c for c in ["POLICY_NUMBER", "BROKER_NAME", "PRODUCT_LINE", "PREMIUM_AMOUNT", "ANOMALY_SCORE"] if c in top_pol]
st.dataframe(top_pol[cols], use_container_width=True, hide_index=True)
st.caption("Records with anomaly_score ≥ 0.95 also carry a natural-language `anomaly_reason` "
           "generated by Cortex in `sp_anomaly_detection`.")
